name: First Workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello, the workflow is running"
      - name: Print Good bye
        run: echo "Good Bye"
