name: Using Secrets with Environment variables while running jobs
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      USER_NAME: ${{secrets.USER_NAME}}
      PASSWORD: ${{secrets.PASSWORD}}
    steps:
      - name: Print user_name environment variable
        run: echo "The user name is ${{env.USER_NAME}}"
      - name: Print password environment variable
        run: echo "The password is ${{env.PASSWORD}}"
